version: "3"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=django_db
      - POSTGRES_USER=dcdrugs
      - POSTGRES_PASSWORD=PNgdEayQuk
  web:
    build: app/
    restart: always
    command: >
      bash -c "python app/manage.py runserver
      & python app/manage.py bot"
    volumes:
      - .:/code
    ports:
      - 80:80
    depends_on:
      - db
