# Generated by Django 3.2.4 on 2021-06-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0004_message_search_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='search_key',
            field=models.TextField(unique=True, verbose_name='Search key'),
        ),
    ]
