# Generated by Django 3.2.4 on 2021-06-06 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0005_alter_message_search_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Search key')),
                ('cost', models.IntegerField(verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time create')),
                ('profiler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.profiler', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Item',
            },
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
