# Generated by Django 3.2.4 on 2021-06-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0006_auto_20210606_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.TextField(verbose_name='Item'),
        ),
    ]
