# Generated by Django 3.2.4 on 2021-06-06 11:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0008_auto_20210606_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
