# Generated by Django 3.2.4 on 2021-06-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0010_auto_20210606_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
