# Generated by Django 3.2.4 on 2021-06-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(verbose_name='User ID')),
                ('name', models.TextField(verbose_name='User name')),
            ],
            options={
                'verbose_name': 'Profiler',
            },
        ),
    ]
