# Generated by Django 3.2.4 on 2021-06-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0002_auto_20210603_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiler',
            name='external_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='User ID'),
        ),
    ]
