# Generated by Django 3.2.4 on 2021-06-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0003_alter_profiler_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='search_key',
            field=models.TextField(default='', unique=True, verbose_name='Search key'),
        ),
    ]
