# Generated by Django 3.2.4 on 2021-06-06 11:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0009_alter_item_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='item',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
